### ISSUE TITLE
GOOGLE_TRANSLATE_API_KEY=XXXXXX ember server

### ISSUE THREAD

**Issue by jianglong98** [szimek/webrtc-translate#14]
It looks not working properly, I have replaced XXXXXX by my Google API Key already.
Is the format changed or any further advices? See log for reference below: 
~/webrtc-translate$ GOOGLE_TRANSLATE_API_KEY=<my key> ember server
module.js:559
    throw err;
    ^
Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (/home/jianglong98/webrtc-translate/node_modules/ember-cli/node_modules/configstore/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)

**Comment by szimek** [comment]
I've just pushed a tiny fix that adds a missing dependency.

I managed to make it work with:
- node 6.x
- yarn 1.5.1
- bower 1.8.2

After cloning the repo run:
```bash
yarn
bower install
GOOGLE_TRANSLATE_API_KEY='xxx' yarn start --environment development
```

Worked for me ;)

**Comment by jianglong98** [comment]
The web service seems working after fix, but the voice button DISAPPEARED and related translation feature didnot work yet. 

~/webrtc-translate$ GOOGLE_TRANSLATE_API_KEY='my key' yarn start --environment development
yarn run v1.5.1
$ ember server --environment development
WARNING: WARNING: Node v9.7.1 has currently not been tested against Ember CLI and may result in unexpected behaviour.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
[BABEL] Note: The code generator has deoptimised the styling of "ember-data/-private.js" as it exceeds the max of "100KB".

Build successful - 14621ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
broccoli-persistent-filter:Babel > [Babel:... | 4125ms              
broccoli-persistent-filter:Babel              | 3737ms              
broccoli-persistent-filter:Babel > [Babel:... | 1657ms              
broccoli-persistent-filter:Babel > [Babel:... | 1308ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
broccoli-persistent-filter:Babel > [Ba... (2) | 5434ms (2717 ms)    
broccoli-persistent-filter:Babel (5)          | 4545ms (909 ms)     
broccoli-persistent-filter:Babel > [Ba... (1) | 1657ms              
broccoli-persistent-filter:Babel > [Ba... (2) | 801ms (400 ms)
